= Vert.x Virtual Threads

Use virtual threads to write Vert.x code that looks like it is synchronous.

You still write the traditional Vert.x code processing events, but you have the opportunity to write synchronous code for complex  workflows and use thread locals in such workflows.

== Usage

To use the virtual threads with Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml]
----
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
</dependency>
----
* Gradle (in your `build.gradle` file):

[source,groovy]
----
dependencies {
  compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
}
----

== Getting started

[source,java]
----
{@link examples.VirtualThreadExamples#gettingStarted}
----

== What this is about

Async/Await for Vert.x

== What this is not about

Blocking on other JDK blocking constructs such as latches, locks, sleep, etc...

NOTE: it remains possible to block on these constructs using `Async.await`

== What you get

By default, Vert.x dispatches events on an event-loop thread.

[source,java]
----
{@link examples.VirtualThreadExamples#whatYouGet1}
----

Using virtual threads with Vert.x requires to run application tasks on a virtual threads

[source,java]
----
{@link examples.VirtualThreadExamples#whatYouGet2}
----

This project implements virtual threads with Vert.x with a race free model. Events are  dispatched to a virtual thread, when this virtual thread awaits an asynchronous result, the pending events are not dispatched until the virtual thread is resumed.

[source,java]
----
{@link examples.VirtualThreadExamples#whatYouGet3}
----

When a virtual thread awaits a future, a new virtual thread can be started to handle new events and avoid blocking the appliction or potential self deadlocks, e.g. in the following example, awaiting the response does not prevent the timer to fire

[source,java]
----
{@link examples.VirtualThreadExamples#whatYouGet4}
----

If you block a virtual thread without `{@link io.vertx.virtualthreads.await.Async`, your application then will behave like a regular worker and events will not be processed until the current task ends.

== Verticles

Virtual thread verticles are actually worker verticles, however a single worker instance is enough to execute it.

[source,java]
----
{@link examples.VirtualThreadExamples#deployVerticle}
----

== Supported primitives

=== Futures

You can await a Vert.x `Future`

[source,java]
----
{@link examples.VirtualThreadExamples#awaitingFutures1}
----

or a JDK `CompletionStage`

[source,java]
----
{@link examples.VirtualThreadExamples#awaitingFutures2}
----

=== Locks

You can lock a `java.util.concurrent.locks`

[source,java]
----
{@link examples.VirtualThreadExamples#awaitingLocks1}
----

== Thread local support

Thread locals are only reliable within the execution of a context task.

[source,java]
----
{@link examples.VirtualThreadExamples#threadLocalSupport1}
----
